version: "3"


volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/moel-asr/data/wordpress 

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/moel-asr/data/mariadb


networks:
  inception:
    name: inception
    driver: bridge


services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: on-failure
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: on-failure
    ports:
      - 443:443
